<a href="https://colab.research.google.com/github/aavinashverma42-dev/Python/blob/main/Day_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pandas Module

In [26]:
import pandas as pd

# people = P1, P2, P3,
# Age = 30, 35, 40,

dict = {"People": ["P1", "P2", "P3"], "Age": [30, 35, 40], "Salary": [200000, 250000, 300000]}

df = pd.DataFrame(dict)
print(df)

  People  Age  Salary
0     P1   30  200000
1     P2   35  250000
2     P3   40  300000

In [27]:
df

  People  Age  Salary
0     P1   30  200000
1     P2   35  250000
2     P3   40  300000

In [ ]:
 #  pd.read_excel("excel file name")

In [21]:
df["People"]

0    P1
1    P2
2    P3
Name: People, dtype: object

In [22]:
df["Age"]

0    30
1    35
2    40
Name: Age, dtype: int64

In [23]:
df["Age"].mean()

np.float64(35.0)

In [28]:
df["Salary"]

0    200000
1    250000
2    300000
Name: Salary, dtype: int64

In [32]:
# df["Key"].operation()
d1 = df["Salary"].sum()
print(f"Sum of Salary: {d1}")

d2 = df["Age"].sum()
print(f"Sum of Age: {d2}")

d3 = df["Salary"].mean()
print(f"Mean of Salary: {d3}")

Sum of Salary: 750000
Sum of Age: 105
Mean of Salary: 250000.0

### More Pandas Operations

In [34]:
# Filtering data: Find people with Age greater than 30
filtered_df = df[df['Age'] > 30]
print("People with Age greater than 30:")
print(filtered_df)

People with Age greater than 30:
  People  Age  Salary
1     P2   35  250000
2     P3   40  300000

In [35]:
# Sorting data: Sort by Salary in descending order
sorted_df = df.sort_values(by='Salary', ascending=False)
print("Data sorted by Salary (descending):")
print(sorted_df)

Data sorted by Salary (descending):
  People  Age  Salary
2     P3   40  300000
1     P2   35  250000
0     P1   30  200000

In [36]:
# Adding a new column: Let's assume everyone gets a bonus of 10% of their salary
df['Bonus'] = df['Salary'] * 0.10
print("DataFrame with new 'Bonus' column:")
print(df)

DataFrame with new 'Bonus' column:
  People  Age  Salary    Bonus
0     P1   30  200000  20000.0
1     P2   35  250000  25000.0
2     P3   40  300000  30000.0